### ISSUE TITLE
reward link at the end

### ISSUE THREAD

**Issue by pixelfabs** [bonartm/quizdown-js#14]
Hi There!

So happy I found this script! Was looking high and low for such a script.

I was wondering, how can I add a reward at the end? I like to add a simple text-link.

Regards,

**Comment by bonartm** [comment]
I like the idea to have a customizable result page. One way to do that could be to specify a point threshold and success message in the quiz options. I currently don't have the time to work on that as my main priority is to increase the quality of the existing code base. But I will leave this issue open and I'm happy for any contributions.
