### ISSUE TITLE
Accessibility - keyboard navigation

### ISSUE THREAD

**Issue by BITS-Editor** [bonartm/quizdown-js#15]
As far as I know, the quiz depends on navigation by mouse. How about navigation by keyboard in order to improve the accessibility?

**Comment by bonartm** [comment]
You can navigate the quiz using the (`Shift`-)`Tab`  and `Enter` keys. Currently, selecting multiple choice or single choice questions is not possible but this needs to change to increase accessibility. 

I don't think that adding custom key navigation is a good idea as it might conflict with websites in which the quiz is embedded. It will also not help with accessibility as there already exist standardized keyboard shortcuts that work on every website.

**Comment by BITS-Editor** [comment]
Agreed, no custom key navigation. The main issue seems to be the access of the answers ("choices").

**Comment by bonartm** [comment]
It should work now. Thanks for the suggestion. It will be included in the next release.

**Comment by BITS-Editor** [comment]
Great, thank you! 

Is it possible to activate the block with the choices when opening a quiz page automatically - or at least when going to the next page with the next question?

The demo https://bonartm.github.io/quizdown-live-editor/ seemingly (?) does not support keyboard navigation.
