### ISSUE TITLE
Fill in the blanks quiz

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [bonartm/quizdown-js#17]
[Fill in the blanks quizzes](https://github.com/bonartm/quizdown-js/blob/main/docs/syntax.md#fill-in-the-blanks-wip) seem to be a work in progress. I'm not sure if it's the same but I'd like to express my desire to have a type of quiz where a question needs to be answered typing a text that matches a specified string.

Any ETA on that type of quiz? I'd be willing to contribute as much as I can or help testing it.

Thank you very much in advance,
Rodrigo

**Comment by bonartm** [comment]
Thanks for the suggestion! Having such a single blank would be much simpler to implement than having a text with several blanks in it. Could you write down some examples for questions and how you would like to write that down in markdown?
Thank you.

**Comment by rodrigoalcarazdelaosa** [comment]
> Could you write down some examples for questions and how you would like to write that down in markdown?

I'm thinking about the [short answer type of question from Google Forms](https://support.google.com/docs/answer/7322334?hl=en#zippy=%2Cshort-answer). I'm a Physics and Chemistry teacher and, specifically, I'd like to have a quiz for practicing nomenclature of chemistry where I ask for example for the formula of a compound, such as _sulfuric acid_, and the correct answer would be H2SO4. Or the other way around: asking for the name of HNO3 and the correct answer would be _nitric acid_ (I guess those strings should be lowercased to avoid mismatches).

As for the markdown syntax for typing that, I'm not really sure which the best way, but this is a suggestion:

```md
{{< quizdown >}}

### Name the following inorganic compound

Sulfuric acid

[x] H2SO4

### Formulate the following inorganic compound

Nitric acid

[x] HNO3

{{< /quizdown >}}
```

**Comment by kheitkamp** [comment]
That's a nice idea!
I would add something to handle case sensitivity:

```
{{< quizdown >}}

### Name the following inorganic compound

HNO<sub>3</sub>

[x] nitric acid > caseSensitive = false

### Formulate the following inorganic compound

Sulfuric acid

[x] H2SO4 

{{< /quizdown >}}
```

I think `false` should be the default value.

**Comment by bonartm** [comment]
You can add a yaml header with options to each specific question. I'd recommend the following format and also use a single checked task list to keep it valid markdown. This will also make it look nice when editing the quizdown in a markdown editor.

```markdown
{{< quizdown >}}

#### Name the following inorganic compound

---
caseSensitive: false

---

HNO<sub>3</sub>

1. [x] nitric acid 

### Formulate the following inorganic compound

Sulfuric acid

1.  [x] H2SO4 

{{< /quizdown >}}
```
