### ISSUE TITLE
results summary page for a quiz consisting of many sub quizzes

### ISSUE THREAD

**Issue by kheitkamp** [bonartm/quizdown-js#18]
I would like to see the possibility to have multiple quiz pages which all belong to a single (super) quiz. So if you visit a summary page you could see the results in all the pages together.

Example:
You navigate to page quizA.html and resolve all the questions on this page. Afterwards you continue on page quizB.html and so on. On each page you see the results of this single page – everything looks and feels just like it is currently. But if you visit summaryResults.html you find a summary of all the quizzes on different pages you visited as long as they belong to the same domain.

**Comment by bonartm** [comment]
Thanks a lot for your suggestions. I like the idea and how you implemented it using `localStorage` and the `			showOverview` option. So as far as I understand the user writes quizzes as before but can also setup a page with an empty "quiz":

```html
<div class="quizdown">
	---
	showOverview: true
	---
</div>
```

Would it make sense to implement this functionality inside the `Quiz` class using static methods? Then the svelte app can check itself whether it should render a results overview or a regular quiz. 

The intension of quizdown is to have a simple, flexible widget that works on all different kind of pages, typically static site generators that use markdown. Is this possible with this feature or can it break certain sites? 

Another solution could also to write quiz data to `localStorage` but leave it to the (advanced) end user to read those values and design a results page with it, if needed. We could provide documentation on how to do it. This would free us from implementing, designing and maintaining a new widget.
