### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by mojomaayan** [bonartm/quizdown-js#23]
Hi, Thanks for the beautiful library! I am very new to JS, trying my hands at a project. I have a question on the installation instructions. When I run npm run build, I see:

```
src/quizdown.ts → public/build/...
[!] Error: 'default' is not exported by node_modules/marked/lib/marked.esm.js, imported by src/customizedMarked.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/customizedMarked.ts (1:7)
1: import marked from 'marked';
          ^
2: import { parse as parseYaml } from 'yaml';
3: // customize tokenizer to include yaml like header blocks
Error: 'default' is not exported by node_modules/marked/lib/marked.esm.js, imported by src/customizedMarked.ts
```

**Comment by bonartm** [comment]
Hi, thank you. I can't replicate the problem and I don't know enough to understand what the issue might be. Have you researched here: https://github.com/markedjs/marked/issues/1692? If you know the issue and you have a fix let us know!
