### ISSUE TITLE
Layout bug in Internet Explorer

### ISSUE THREAD

**Issue by BITS-Editor** [bonartm/quizdown-js#24]
Hi!

Any chance to fix the layout under Internet Explorer 1809 for Windows 10?

Instead of showing the box with the questions and options, there is plain text like this:

> --- primary_color: '#1C90F3' title_color: black shuffle_questions: false shuffle_answers: true shuffle_answers: true --- ## Was sind Computerviren? > Computerviren sind kleine Programmteile, die sich unbemerkt an ein anderes Programm anhängen und so auf fremden Rechnern ausgeführt werden können. 1. [x] Kleine Programmteile, die sich unbemerkt an ein anderes Programm anhängen und so auf fremden Rechnern ausgeführt werden können.> > **Richtige Antwort! Lösungsbuchstabe S** 2. [ ] Mikroskopisch...

Thanks!

**Comment by bonartm** [comment]
IE is considered outdated and I don't have any plans to support it. I will add a note in the README though.
