### ISSUE TITLE
Option to highlight correct answer after the end of quiz

### ISSUE THREAD

**Issue by ttheng3810** [bonartm/quizdown-js#26]
Hello, thanks for implementing this library, it really helped a lot!

I just wonder if it is possible to implement a quiz option such that the correct solutions to all the quiz questions will be revealed (highlighted) after the end of quiz where the end user is shown the list of questions with a tick or cross symbol at the side, like when the end user clicks on a question from the list.

Thank you!

**Comment by bonartm** [comment]
Thanks for the suggestions! This will be worked on as part of #12.
