### ISSUE TITLE
Tab key navigation on first quiz page broken

### ISSUE THREAD

**Issue by BITS-Editor** [bonartm/quizdown-js#32]
**See update below! https://github.com/bonartm/quizdown-js/issues/32#issuecomment-1339503675 **

When opening the first page of a quiz, you can access the possible answers using the tab key and the cursor keys.

But, unlike in a previous release of quizdown-js, the tab key on the first page does not allow you to leave the answer box. As a result, there is no keyboard navigation availabe to highlight the arrow buttons etc. below the answer box to get to the second question / page of a quiz.

However, when you click on the arrow right-button by mouse, on the second page the tab key does work and allows access to all buttons as it should be.

So it seems that only the first page of a quiz is buggy.

Please check here for an example
https://bits-training.github.io/01-lektion-e-mails/90.quiz-e-mails/

and here for the former, working version:
https://bits-training.de/training/030-lektion-e-mail/90.quiz-e-mails/

and here for the manual describing the way it should work
https://bits-training.github.io/barrierefreiheit/

**Comment by BITS-Editor** [comment]
Sorry for rushing, but have you cut your eyes onto this issue yet? Thanks!

**Comment by bonartm** [comment]
I currently don't find time to work on this project. Unfortunately, don't expect any updates soon.

**Comment by BITS-Editor** [comment]
> I currently don't find time to work on this project. Unfortunately, don't expect any updates soon.

OK, we will keep this issue open in our repository, too.

**Comment by BITS-Editor** [comment]
UPDATE:
It seems that only Chrome-based browsers are affected, not Firefox.
