### ISSUE TITLE
save quiz results

### ISSUE THREAD

**Issue by eisler** [bonartm/quizdown-js#35]
I would like to automatically save quiz results. 
Is it possible to do so and if so, could you please provide me with a guide?
Can I use a callback or an event to save quiz results after they have been processed by the parser? 
If so, could you please provide me with an example?

**Comment by trickybitch** [comment]
Hi @eisler , are you able to share an example of how you did it?

I'd like to be able to reference the results in another part of my webpage.

Cheers

**Comment by trickybitch** [comment]
> 

It's not pretty but I ended up just saving them into a JS variable that I can reference later on,

Cheers

**Comment by eisler** [comment]
Hi @trickybitch, that sounds like a nice start. I would like to see the result.
