### ISSUE TITLE
Deobfuscation

### ISSUE THREAD

**Issue by GrimPixel** [bonartm/quizdown-js#36]
What is the point of cramming all code into one line? We have JavaScript deobfuscators. If someone wants to figure your code out, they can use them as they wish, with the claimer of “Copyright (c) Microsoft Corporation.” gone.

Even after deobfuscation, there are still seven thousand lines in a file. I don't understand how you would like other people to contribute to such scripts.

**Comment by bonartm** [comment]
Have a look into the `src` folder (https://github.com/bonartm/quizdown-js/tree/main/src), this is where you find the actual source code for the project. The files that you are referring to are generated automatically through the build process. You can read more about it here: https://dev.to/benjithorpe/file-structure-of-svelte-apps-18p0
