### ISSUE TITLE
Translation of the buttons and texts

### ISSUE THREAD

**Issue by andi-blafasl** [bonartm/quizdown-js#4]
Hi bonartm,

I realy like your Quiz Engine and the Hugo Plugin you wrote. I realy like to use it in a projekt I'm currently on. 
Unfortunately, all texts and buttons are only available in English and the website is currently only being developed in German. The majority of users are also not good at English and the hurdle would be too big.
Is there an easy way to translate all texts? Search and replace in the final minified JS-file is a bit confusing and I'm not familiar with npm development ;-)
A multilingual version woud be very nice! Especially in combination with the multilingual function in HUGO.

**Comment by bonartm** [comment]
Thanks for the suggestion and for using the library. It should be fairly easy to implement using https://github.com/kaisermann/svelte-i18n.

**Comment by bonartm** [comment]
Language is now detected based on browser settings and text is set accordingly. Currently only german and english is supported but new languages can be added very easily. Thanks for the suggestion, I've learned a lot!
