### ISSUE TITLE
Bug with results when restarting the Quiz

### ISSUE THREAD

**Issue by andi-blafasl** [bonartm/quizdown-js#7]
I realy like your new released version! It's looking great and with the new feature for translation and comments to the answers this tool is perfekt for our project 👍 
But there seems to be a bug with the Icons if I restart the Test. Even if I select the correct answer, the Icons for a false answer is displayed.

You can check it out here: https://bits-training.github.io/030-lektion-e-mail/90.quiz-e-mails/

**Comment by bonartm** [comment]
Thanks! There was a bug for single choice question. It should work now.
